### ISSUE TITLE
Resource not found: person

### ISSUE THREAD

**Issue by cyan-color** [nagarjunvinukonda/Gazebo-Human-and-obstacle-tracker#3]
I launch the `roslaunch turtlebot3_gazebo  turtlebot3_env.launch`
![2021-05-07 17-25-05屏幕截图](https://user-images.githubusercontent.com/55053862/117429576-c65f0c00-af59-11eb-8d83-5a14e2441d66.png)

**Comment by nagarjunvinukonda** [comment]
Hello Cyan, thank you for posting your error. Thats because it require the person package. Let me update the git. It should solve the problem.
